# WARNING: Temporary alias routes generated by Route Doctor.
# Review carefully and remove after templates are corrected.
from flask import redirect, url_for

def register_alias_routes(app):
    @app.route('/__alias__/data_management_export_data', endpoint='data_management.export_data')
    def __alias_data_management_export_data():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_import_data'))

    @app.route('/__alias__/notifications_index', endpoint='notifications.index')
    def __alias_notifications_index():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('solutions.index'))

    @app.route('/__alias__/notifications_mark_all_read', endpoint='notifications.mark_all_read')
    def __alias_notifications_mark_all_read():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('notifications_config.test_escalation'))

    @app.route('/__alias__/notifications_mark_read', endpoint='notifications.mark_read')
    def __alias_notifications_mark_read():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('notifications_config.create_setting'))

    @app.route('/__alias__/admin_audit_trail', endpoint='admin_audit_trail')
    def __alias_admin_audit_trail():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_audit_logs'))

    @app.route('/__alias__/admin_audit_trail', endpoint='admin.audit_trail')
    def __alias_admin_audit_trail():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_audit_logs'))

    @app.route('/__alias__/admin_assign_department', endpoint='admin.assign_department')
    def __alias_admin_assign_department():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_help_center'))

    @app.route('/__alias__/admin_regional_settings', endpoint='admin.regional_settings')
    def __alias_admin_regional_settings():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_organization_settings'))

    @app.route('/__alias__/admin_test_rule', endpoint='admin.test_rule')
    def __alias_admin_test_rule():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_test_triage_rule'))

    @app.route('/__alias__/admin_toggle_rule', endpoint='admin.toggle_rule')
    def __alias_admin_toggle_rule():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_toggle_triage_rule'))

    @app.route('/__alias__/admin_delete_rule', endpoint='admin.delete_rule')
    def __alias_admin_delete_rule():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_delete_triage_rule'))

    @app.route('/__alias__/data_management_data_retention_page', endpoint='data_management.data_retention_page')
    def __alias_data_management_data_retention_page():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('dashboards.manager_dashboard'))

    @app.route('/__alias__/epics_view_epics', endpoint='epics.view_epics')
    def __alias_epics_view_epics():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('review.review_epics'))

    @app.route('/__alias__/epics_edit_epic', endpoint='epics.edit_epic')
    def __alias_epics_edit_epic():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('projects.edit_project'))

    @app.route('/__alias__/epics_edit_story', endpoint='epics.edit_story')
    def __alias_epics_edit_story():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('projects.edit_milestone'))

    @app.route('/__alias__/problems_problem_detail', endpoint='problems.problem_detail')
    def __alias_problems_problem_detail():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('problems.classify_problem'))

    @app.route('/__alias__/projects_project_detail', endpoint='projects.project_detail')
    def __alias_projects_project_detail():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('projects.project_backlog'))

    @app.route('/__alias__/admin_admin_dashboard', endpoint='admin.admin_dashboard')
    def __alias_admin_admin_dashboard():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_dashboard'))

    @app.route('/__alias__/projects_list_projects', endpoint='projects.list_projects')
    def __alias_projects_list_projects():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('projects.edit_project'))

    @app.route('/__alias__/projects_milestones_list', endpoint='projects.milestones_list')
    def __alias_projects_milestones_list():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('projects.new_milestone'))

    @app.route('/__alias__/platform_admin_dashboard', endpoint='platform_admin.dashboard')
    def __alias_platform_admin_dashboard():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_dashboard'))

    @app.route('/__alias__/platform_admin_waitlist_management', endpoint='platform_admin.waitlist_management')
    def __alias_platform_admin_waitlist_management():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_test_triage_rule'))

    @app.route('/__alias__/platform_admin_logout', endpoint='platform_admin.logout')
    def __alias_platform_admin_logout():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('auth.logout'))

    @app.route('/__alias__/platform_admin_export_csv', endpoint='platform_admin.export_csv')
    def __alias_platform_admin_export_csv():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_data_export'))

    @app.route('/__alias__/platform_admin_analytics', endpoint='platform_admin.analytics')
    def __alias_platform_admin_analytics():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('help_api.get_analytics'))

    @app.route('/__alias__/platform_admin_toggle_contacted', endpoint='platform_admin.toggle_contacted')
    def __alias_platform_admin_toggle_contacted():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_toggle_triage_rule'))

    @app.route('/__alias__/platform_admin_delete_entry', endpoint='platform_admin.delete_entry')
    def __alias_platform_admin_delete_entry():
        # TEMP: redirect missing endpoint to best match
        return redirect(url_for('admin_delete_help_category'))

