services:
- type: web
  name: deciframe-app
  env: python
  repo: https://github.com/LamiKols/Deciframe.git
  branch: main
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2"
  autoDeploy: true
  envVars:
    - key: FLASK_ENV
      value: production
