"""
Test suite for AI Solution Recommendation Engine
"""

import pytest
import json
from unittest.mock import patch, MagicMock
from models import User, Department, Problem, Solution
from extensions import db

class MockOpenAIResponse:
    def __init__(self, content):
        self.choices = [MagicMock()]
        self.choices[0].message.content = content

@pytest.fixture
def solutions_test_client(app):
    """Create test client for solutions tests"""
    with app.test_client() as client:
        with app.app_context():
            # Create test department
            dept = Department(name='Test Department', level=1)
            db.session.add(dept)
            db.session.commit()
            
            # Create test user with Manager role
            user = User(
                email='manager@example.com',
                name='Test Manager',
                role='Manager',
                department_id=dept.id
            )
            user.set_password('testpass')
            db.session.add(user)
            db.session.commit()
            
            # Create test problem
            problem = Problem(
                title='Test Problem for Solutions',
                description='This is a test problem that needs AI-generated solutions for testing purposes.',
                priority='High',
                status='Open',
                department_id=dept.id,
                created_by=user.id
            )
            db.session.add(problem)
            db.session.commit()
            
            yield client, user, problem

def test_suggest_solutions_requires_auth(solutions_test_client):
    """Test that solutions suggestion endpoint requires authentication"""
    client, user, problem = solutions_test_client
    
    response = client.post('/api/ai/suggest-solutions', 
                          json={'problem_id': problem.id})
    assert response.status_code == 401

@patch('ai.routes.OpenAI')
def test_suggest_solutions_success(mock_openai_class, solutions_test_client):
    """Test successful solution suggestion generation"""
    client, user, problem = solutions_test_client
    
    # Mock OpenAI response
    mock_response_text = """
**Solution 1: Process Automation Implementation**
Description: Implement automated workflows to eliminate manual processes and reduce human error. This solution includes workflow design, system integration, and user training to ensure smooth adoption.

**Solution 2: Technology Infrastructure Upgrade**
Description: Upgrade the underlying technology infrastructure to support increased performance and scalability. This includes server optimization, database tuning, and network improvements.

**Solution 3: User Training and Support Program**
Description: Develop comprehensive training programs and enhanced support systems to improve user competency and reduce support requests through better user education.
"""
    
    mock_client = MagicMock()
    mock_openai_class.return_value = mock_client
    mock_client.chat.completions.create.return_value = MockOpenAIResponse(mock_response_text)
    
    # Authenticate user
    with client.session_transaction() as sess:
        sess['_user_id'] = str(user.id)
        sess['_fresh'] = True
    
    # Test API call
    response = client.post('/api/ai/suggest-solutions', 
                          json={'problem_id': problem.id})
    
    assert response.status_code == 200
    data = response.get_json()
    
    assert 'variants' in data
    assert 'problem_id' in data
    assert 'problem_title' in data
    assert len(data['variants']) == 3
    
    # Check first solution structure
    solution1 = data['variants'][0]
    assert 'name' in solution1
    assert 'description' in solution1
    assert 'Process Automation Implementation' in solution1['name']

def test_suggest_solutions_with_invalid_problem(solutions_test_client):
    """Test solution suggestion with non-existent problem"""
    client, user, problem = solutions_test_client
    
    # Authenticate user
    with client.session_transaction() as sess:
        sess['_user_id'] = str(user.id)
        sess['_fresh'] = True
    
    # Test with invalid problem ID
    response = client.post('/api/ai/suggest-solutions', 
                          json={'problem_id': 99999})
    
    assert response.status_code == 404

def test_create_solution_success(solutions_test_client):
    """Test successful solution creation"""
    client, user, problem = solutions_test_client
    
    # Authenticate user
    with client.session_transaction() as sess:
        sess['_user_id'] = str(user.id)
        sess['_fresh'] = True
    
    solution_data = {
        'problem_id': problem.id,
        'name': 'Test AI Generated Solution',
        'description': 'This is a comprehensive solution generated by AI to address the identified problem with specific implementation steps.'
    }
    
    response = client.post('/solutions/new', 
                          json=solution_data)
    
    assert response.status_code == 200
    data = response.get_json()
    
    assert data['success'] is True
    assert 'solution_id' in data
    assert 'message' in data
    
    # Verify solution was created in database
    solution = Solution.query.filter_by(name='Test AI Generated Solution').first()
    assert solution is not None
    assert solution.problem_id == problem.id
    assert solution.created_by == user.id

def test_create_solution_requires_manager_role(solutions_test_client):
    """Test that solution creation requires Manager role or above"""
    client, user, problem = solutions_test_client
    
    # Change user role to Staff
    user.role = 'Staff'
    db.session.commit()
    
    # Authenticate user
    with client.session_transaction() as sess:
        sess['_user_id'] = str(user.id)
        sess['_fresh'] = True
    
    solution_data = {
        'problem_id': problem.id,
        'name': 'Test Solution',
        'description': 'Test description'
    }
    
    response = client.post('/solutions/new', 
                          json=solution_data)
    
    assert response.status_code == 403
    data = response.get_json()
    assert 'Insufficient permissions' in data['error']

def test_create_solution_missing_data(solutions_test_client):
    """Test solution creation with missing required data"""
    client, user, problem = solutions_test_client
    
    # Authenticate user
    with client.session_transaction() as sess:
        sess['_user_id'] = str(user.id)
        sess['_fresh'] = True
    
    # Test with missing name
    response = client.post('/solutions/new', 
                          json={'problem_id': problem.id, 'description': 'Test'})
    
    assert response.status_code == 400
    data = response.get_json()
    assert 'required' in data['error']

def test_parse_solutions_function():
    """Test the parse_solutions function directly"""
    from ai.routes import parse_solutions
    
    sample_response = """
**Solution 1: Automated Testing Framework**
Description: Implement comprehensive automated testing framework including unit tests, integration tests, and end-to-end testing to improve code quality and reduce bugs in production.

**Solution 2: Code Review Process Enhancement**
Description: Establish mandatory code review processes with clear guidelines, automated tools, and peer review requirements to maintain high code quality standards.

**Solution 3: Performance Monitoring System**
Description: Deploy real-time performance monitoring and alerting systems to proactively identify and address performance issues before they impact users.
"""
    
    solutions = parse_solutions(sample_response)
    
    assert len(solutions) == 3
    assert solutions[0]['name'] == 'Automated Testing Framework'
    assert 'comprehensive automated testing' in solutions[0]['description']
    assert solutions[1]['name'] == 'Code Review Process Enhancement'
    assert solutions[2]['name'] == 'Performance Monitoring System'

def test_generate_intelligent_solutions():
    """Test intelligent solution generation"""
    from ai.routes import generate_intelligent_solutions
    from models import Problem, PriorityEnum
    
    # Create test problem with performance issue
    problem = Problem(
        title='System Performance Issues',
        description='The application is very slow during peak hours and users are experiencing timeouts',
        priority=PriorityEnum.High
    )
    
    solutions = generate_intelligent_solutions(problem)
    
    assert len(solutions) == 3
    assert all('name' in s and 'description' in s for s in solutions)
    assert 'Performance' in solutions[0]['name']
    assert 'Infrastructure' in solutions[1]['name'] or 'Optimization' in solutions[1]['name']