"""
Generates a temporary alias route snippet for unresolved endpoints based on MISSING_ROUTES.csv.
Usage:
  python scripts/generate_route_aliases.py > ALIAS_ROUTES.py
Then manually review and (optionally) include into your Flask app during transition.
"""
import csv, sys

csv_path = "MISSING_ROUTES.csv"

print("# WARNING: Temporary alias routes generated by Route Doctor.")
print("# Review carefully and remove after templates are corrected.")
print("from flask import redirect, url_for")
print("")
print("def register_alias_routes(app):")
try:
    with open(csv_path, encoding="utf-8") as f:
        r = csv.DictReader(f)
        emitted = set()
        for row in r:
            missing = (row.get("missing_endpoint") or row.get("missing") or "").strip()
            best = (row.get("best_match") or "").strip()
            if not missing or not best or (missing in emitted): 
                continue
            safe_missing = missing.replace('.', '_')
            print(f"    @app.route('/__alias__/{safe_missing}', endpoint='{missing}')")
            print(f"    def __alias_{safe_missing}():")
            print(f"        # TEMP: redirect missing endpoint to best match")
            print(f"        return redirect(url_for('{best}'))")
            print("")
            emitted.add(missing)
except FileNotFoundError:
    print("    # No MISSING_ROUTES.csv found; run route_doctor first.")